### ISSUE TITLE
Составить текст куки-баннера

### ISSUE THREAD

**Issue by birthdaysgift** [week-password/wisher#12]
В результате [обсуждения](https://github.com/week-password/wisher/discussions/8) было решено в MVP добавить куки-баннер, который будет предупреждать пользователя о том, что наш сайт использует куки, т.к. это необходимо по закону:

> Согласно ФЗ «О персональных данных» и GDPR куки-файлы и иные идентификаторы пользователя относятся к персональным данным, поскольку позволяют теоретически определить конкретного субъекта или выделить его среди других лиц.

В рамках MVP нам достаточно простого текста, т.к. пока что нас никто не собирается активно преследовать по закону, да и пользователи приложения в основном это наши друзья и знакомые.

В рамках данного тикета необходимо составить текст для куки-баннера и разместить его в вики - на странице **Юридические документы. Cookie-баннер**

В идеале куки-баннер должен содержать информацию о:
1. cобираемых куки-файлах и иных идентификаторах
2. целях их сбора
3. сроках хранения в памяти устройства
4. третьих лицах, которым передают данные
а также возможность принять все идентификаторы, кастомизировать их выбор или полностью отказаться от них (помимо строго обязательных). Информацию можно также разместить на отдельной странице, к которой пользователь может перейти в любой момент своего сеанса, чтобы изменить настройки или узнать ответы на интересующие вопросы.

**Comment by birthdaysgift** [comment]
Подбробности о различных видах куки можно посмотреть в [обсуждении](https://github.com/week-password/wisher/discussions/8#discussioncomment-5209694).

**Comment by Rey-Lane** [comment]
Кажется, что делать отдельный баннер для cookie не нужно, так как мы используем только технические cookie, которые нужны для корректной и удобной работы сервиса. Мы лишь должны внести пункт о cookie в нашу `политику конфиденциальности`, где будет сказано какие cookie, для чего и как мы используем. Стоит учитывать, что баннер с cookie мы должны были показывать уже после процесса регистрации (в котором пользователь соглашается с политикой конфиденциальности). Поэтому явной пользы в баннере нет.

Если на душе не спокойно, то можно сделать простую всплывашку по типу:

> Добро пожаловать в WIsher - сервис по исполнению желаний!
> 
> Мы используем технические cookie, чтобы улучшить работу и предоставить вам лучший опыт использования нашего сервиса. Наши cookie не собирают информацию о вашей личности и не передают ее третьим лицам.
> 
> Подробнее о нашей политике использования cookie вы можете узнать в нашей Политике конфиденциальности.

**Comment by birthdaysgift** [comment]
Текст всплывашки очень хорош! Думаю, действительно стоит его добавить.

**Comment by fowesn** [comment]
Мне тоже нравится, давайте добавим)

Ещё написала несколько слов о документах (в т.ч. о cookie) [здесь](https://github.com/week-password/wisher/discussions/8).

**Comment by birthdaysgift** [comment]
Судя по всему с текстом мы определились. @Rey-Lane, можешь добавить его в вики вишера на страницу **Юридические документы. Cookie-баннер**? Тогда можно будет закрыть задачу и подумать как он будет выглядеть дизайнах.

**Comment by Rey-Lane** [comment]
Добавил в [wiki](https://github.com/week-password/wisher/wiki/%D0%AE%D1%80%D0%B8%D0%B4%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B#cookie-%D0%B1%D0%B0%D0%BD%D0%BD%D0%B5%D1%80), тикет закрыл.
