### ISSUE TITLE
Составить текст политики конфиденциальности

### ISSUE THREAD

**Issue by birthdaysgift** [week-password/wisher#13]
В результате [обсуждения](https://github.com/week-password/wisher/discussions/8) было решено в MVP добавить политику конфиденциальности, где мы должны написать, какие данные мы собираем, как их обрабатываем, храним, передаём ли третьим лицам или нет, для чего используем.

В рамках MVP нам достаточно простого текста, т.к. пока что нас никто не собирается активно преследовать по закону, да и пользователи приложения в основном это наши друзья и знакомые.

В рамках данного тикета необходимо составить текст для пользовательского соглашения и разместить его в вики - на странице **Юридические соглашения. Политика конфиденциальности**

Примерный шаблон для текста:

>  ### Общие положения
> 
> Данная политика конфиденциальности определяет порядок сбора, использования, хранения и раскрытия персональных данных пользователей сайта [www.foo.com](http://www.foo.com/) (далее – «Сайт»). Данная политика конфиденциальности действует в отношении всех персональных данных, которые могут быть получены от пользователей Сайта.
> 
>  ### Сбор и использование персональных данных
> 
> 2.1. На Сайте пользователь может оставить свое имя и адрес электронной почты для получения персонализированных сообщений по электронной почте.
> 
> 2.2. Сбор персональных данных осуществляется только после получения согласия пользователя на обработку его персональных данных.
> 
> ### Хранение персональных данных
> 
> 3.1. Персональные данные пользователей хранятся на серверах, расположенных в Российской Федерации.
> 
> 3.2. Хранение персональных данных осуществляется в соответствии с применимым законодательством Российской Федерации.
> 
>  ### Раскрытие персональных данных
> 
> 4.1. Раскрытие персональных данных пользователей Сайта может осуществляться только в случаях, предусмотренных действующим законодательством Российской Федерации.
> 
> ### Защита персональных данных
> 
> 5.1. Для защиты персональных данных пользователя Сайта используются технические и организационные меры безопасности, соответствующие рискам потери, неправомерного или непреднамеренного доступа, раскрытия, изменения или уничтожения персональных данных.

**Comment by Rey-Lane** [comment]
### Предлагаемый вариант

Уважаемый пользователь,

Мы ценим Ваше доверие и стремимся обеспечить наивысший уровень защиты Ваших персональных данных. Настоящая Политика конфиденциальности (далее – «Политика») определяет порядок сбора, использования, хранения и защиты Ваших персональных данных на сайте Wisher (далее – «Сайт»).

### Сбор и использование персональных данных

Мы собираем только те персональные данные, которые Вы сами предоставляете нам в процессе использования Сайта. Они могут включать Ваше имя, адрес электронной почты, информацию о Вашем списке желаний, описание профиля и другие данные, которыми Вы решите поделиться с нами. 

Мы используем эти данные только в соответствии с целями, для которых они были предоставлены, в том числе для:

- обеспечения доступа к Сайту и использование функционала Сайта;
- отправки персонализированных сообщений по электронной почте (о смене пароля, об изменении Политики и других случаях);

###   Технические cookie

Мы используем технические cookie для обеспечения корректной работы Сайта и предоставления Вам лучшего опыта использования нашего сервиса. Cookie – это небольшие файлы, которые отправляются на Ваш компьютер при посещении Сайта. Наши cookie не собирают никакой личной информации о пользователе и не могут быть использованы для отслеживания действий на Сайте.

Некоторые из задач, выполняемых нашими техническими cookie, включают в себя:

- Сохранение предпочтений пользователей и настроек Сайта;
- Поддержание текущей сессии пользователя;
- Обеспечение безопасности Сайта.

Вы можете отключить технические cookie в настройках вашего браузера, но это может повлиять на функциональность сервиса и привести к неправильной его работе.

Мы не используем технические cookie для сбора или хранения каких-либо персональных данных о пользователе.

### Защита персональных данных

Мы гарантируем конфиденциальность Ваших персональных данных и не передаем их третьим лицам, за исключением случаев, предусмотренных законодательством РФ.

Часть ваших персональных данных будет доступна другим пользователям приложения на основании функций предоставляемых приложением. Например, публичная информация профиля, список желаний и др.

### Изменения Политики

Мы оставляем за собой право вносить изменения в настоящую Политику. Обновленная версия Политики будет опубликована на Сайте. Мы также уведомим Вас об этих изменениях по электронной почте.

Благодарим Вас за использование нашего сервиса!

С уважением,
Команда Wisher

**Comment by birthdaysgift** [comment]
Текст мне нравится, кажется здесь есть всё, что нужно.

Заметил пару моментов:

1. Я не уверен, но вроде как при вежливом обращении "Вы" и "Ваши" надо писать с большой буквы. Может кто знает точнее.

3. "Это может" -> "Они могут":
    > Мы собираем только те персональные данные, которые вы сами предоставляете нам в процессе использования Сайта. **Они могут** включать ваше имя, адрес электронной почты, информацию о вашем списке желаний, описание профиля и другие данные, которыми вы решите поделиться с нами.

4. "других случаев" -> "других случаях":
    > - отправки персонализированных сообщений по электронной почте (о смене пароля, об изменении Политики и других случа**ях**);

5. "Эти cookie" -> "Наши cookie":
    > Cookie – это небольшие файлы, которые отправляются на ваш компьютер при посещении Сайта. **Наши** cookie не собирают никакой личной информации о пользователе и не могут быть использованы для отслеживания действий на Сайте.

6. "и может привести" -> "и привести":
    > но это может повлиять на функциональность сервиса **и привести** к неправильной его работе.

**Comment by Rey-Lane** [comment]
Согласен с замечаниями
Что касается первого пункта, то, вроде бы, нужно писать с большой буквы, так как это уважительное обращение к конкретному пользователю ([тык](http://new.gramota.ru/spravka/letters/51-rubric-88)).
Но есть инфа о том, что на web страницах пишут с маленькой ([тык](https://newslab.ru/article/142989) и [тык](https://rg.ru/2009/06/25/vy.html))

Пока что временно сделал всё с большой

**Comment by fowesn** [comment]
В целом мне всё нравится, только хочу уточнить пару моментов:

> Сохранение предпочтений пользователей по поводу языка и настроек Сайта;

У нас сейчас не планируется никаких настроек сайта и выбора языка, это ок, что мы напишем о функциях, которых нет? Мне кажется, это хорошо, потому что в будущем не придётся на каждую новую фичу, использующую cookie, менять текст политики, просто думаю, корректно ли это будет, пока у нас нет этих функций

Текст про сбор и использование персональных данных предполагает, что мы пошарим их другим пользователям (публичную информацию профиля, такую как имя и список желаний)? Может, нам нужно добавить уточнение об этом?

**Comment by birthdaysgift** [comment]
> @fowesn:
> У нас сейчас не планируется никаких настроек сайта и выбора языка, это ок, что мы напишем о функциях, которых нет?

Можно попытаться аккуратно обойти этот момент с помощью такой более размытой формулировки:

> Сохранение предпочтений пользователей и настроек Сайта;

***

> @fowesn:
> Текст про сбор и использование персональных данных предполагает, что мы пошарим их другим пользователям (публичную информацию профиля, такую как имя и список желаний)? Может, нам нужно добавить уточнение об этом?

Кажется да, это стоит добавить. Можно попробовать такую формулировку:

> Мы гарантируем конфиденциальность Ваших персональных данных и не передаем их третьим лицам, за исключением случаев, предусмотренных законодательством РФ.
>
> Часть ваших персональных данных будет доступна другим пользователям приложения на основании функций предоставляемых приложением. Например, публичная информация профиля, список желаний и др.

**Comment by Rey-Lane** [comment]
Согласен, хорошее замечание)

**Comment by birthdaysgift** [comment]
@Rey-Lane, скоро @fowesn будет приступать к добавлению наших юридических документов на фронт, поэтому хотелось бы финализировать их.

Необходимо внести заапрувленные правки и запостить в вики, если у тебя есть время.

**Comment by Rey-Lane** [comment]
Комментарий с текстом политики отредактировал, версия должна быть актуальной, проверьте по диагонали на всякий случай)

**Comment by birthdaysgift** [comment]
Проверил, добавил в [вики](https://github.com/week-password/wisher/wiki/%D0%AE%D1%80%D0%B8%D0%B4%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B).
