### ISSUE TITLE
Составить текст согласия на обработку персональных данных

### ISSUE THREAD

**Issue by birthdaysgift** [week-password/wisher#16]
В результате [обсуждения](https://github.com/week-password/wisher/discussions/8) было решено в MVP добавить согласие на обработку персональных данных, чтобы пользователь дал своё согласие на обработку данных по тем методам, которые описаны в политике конфиденциальности.

В рамках MVP нам достаточно простого текста, т.к. пока что нас никто не собирается активно преследовать по закону, да и пользователи приложения в основном это наши друзья и знакомые.

В рамках данного тикета необходимо составить текст для согласия на обработку персональных данных и разместить его в вики - на странице **Юридические соглашения. Согласие на обработку персональных данных**. Возможно этот текст должен быть объединен с текстом Политики конфиденциальности и соответственно записан не на отдельной вики странице, а на странице **Юридические соглашения. Политика конфиденциальности**, т.к.:

> @Rey-Lane 
> В целом, их можно представить в виде единого документа, не разделяя

**Comment by Rey-Lane** [comment]
### Предлагаемый вариант

Уважаемый пользователь,

Для использования нашего сервиса **Wisher** необходимо предоставить некоторую персональную информацию, включая имя и адрес электронной почты. Мы стремимся обеспечить наивысший уровень защиты Ваших персональных данных, поэтому просим Вас внимательно ознакомиться с условиями настоящего Согласия на обработку персональных данных (далее – «Соглашение»).

Предоставляя нам свои персональные данные, вы даете согласие на их обработку в соответствии с настоящим Соглашением. Обработка персональных данных будет осуществляться на основании законодательства РФ и Политики конфиденциальности (добавить гиперссылку).
Мы можем использовать Ваши персональные данные для следующих целей:

- обеспечения работы сервиса Wisher и его функциональных возможностей;
- обеспечения взаимодействия с вами, включая предоставление информации о наших услугах;
- улучшения нашего сервиса и создания наиболее удобных условий его использования.

Мы гарантируем конфиденциальность Ваших персональных данных и не передаем их третьим лицам, за исключением случаев, предусмотренных нашей Политикой конфиденциальности (добавить гиперссылку) и законодательством РФ.


Благодарим вас за использование нашего сервиса!

С уважением,
Команда Wisher

**Comment by birthdaysgift** [comment]
По тексту мне всё нравится.

Надо определиться как реализовать это:
> Вы можете в любой момент отозвать свое согласие на обработку персональных данных

И т.к. этот вопрос относится к тексту согласия очень косвено, то предлагаю здесь обсуждать только текст, а функционал "отзыва" можно обсудить в отдельном [discussion](https://github.com/week-password/wisher/discussions/18).

**Comment by fowesn** [comment]
Мне нравится)
Насчёт отзыва согласия я правильно понимаю, что решили не делать и, соответственно, строки про отзыв согласия тоже не будет?

И ещё мне бы хотелось немного поменять это предложение:
> Обработка персональных данных будет осуществляться на основании законодательства РФ и Политики конфиденциальности, размещенной по адресу `ссылка на политику`.

А именно, хотелось бы сделать текст "Политики конфиденциальности" гиперссылкой и убрать ", размещенной по адресу `ссылка на политику`":

> Обработка персональных данных будет осуществляться на основании законодательства РФ и <ins>Политики конфиденциальности</ins>.

**Comment by Rey-Lane** [comment]
Да, так будет лучше, спасибо. Всё это писалось в неком порыве и потоке, поэтому некая эстетика может проседать)

**Comment by birthdaysgift** [comment]
@Rey-Lane, скоро @fowesn будет приступать к добавлению наших юридических документов на фронт, поэтому хотелось бы финализировать их.

Необходимо внести заапрувленные правки и запостить в вики, если у тебя есть время.

**Comment by Rey-Lane** [comment]
Комментарий с текстом отредактировал. Проверьте на всякий случай по-быстрому)
Так как в политике мы добавили пункт про то, что персональные данные используются сервисом и могут быть видны пользователям, я немного расширил пункт про законодательство.

```Мы гарантируем конфиденциальность Ваших персональных данных и не передаем их третьим лицам, за исключением случаев, предусмотренных нашей Политикой конфиденциальности (добавить гиперссылку) и законодательством РФ.```

Посмотрите, как вам. Не забудьте добавить 2 гиперссылки и удалить их упоминание из текста)

**Comment by birthdaysgift** [comment]
Проверил, внёс в [вики](https://github.com/week-password/wisher/wiki/%D0%AE%D1%80%D0%B8%D0%B4%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B).
